logging:
  level:
    org.flowable.ui.modeler.rest.app: debug
#    root: debug
server:
  port: 8081
  servlet:
    context-path: "/flowable-modeler-demo"
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/flowable-modeler-demo2?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: flowable-modeler-demo


mybatis-plus:
  type-aliases-package: com.example.oldguy.modules.app.dao.entities


